# Generated by Django 5.1.1 on 2024-09-23 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academica', '0002_alumno_email_alumno_genero_alumno_segundo_apellido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='segundo_apellido',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='segundo_nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='docente',
            old_name='segundo_apellido',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='docente',
            old_name='segundo_nombre',
            new_name='nombre',
        ),
    ]
