# Generated by Django 5.1.1 on 2024-09-23 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academica', '0003_rename_segundo_apellido_alumno_apellido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='carrera',
        ),
    ]
