# Generated by Django 5.1.1 on 2024-09-30 13:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academica', '0005_curso_semestre_inscripcion_asistencia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('capacidad', models.PositiveIntegerField()),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='inscripcion',
            old_name='calificacion',
            new_name='calificacion_final',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='docente',
        ),
        migrations.AddField(
            model_name='alumno',
            name='correo_madre',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='correo_padre',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='aula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academica.aula'),
        ),
        migrations.CreateModel(
            name='CursoProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_titular', models.BooleanField(default=False)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academica.curso')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academica.docente')),
            ],
            options={
                'unique_together': {('curso', 'docente')},
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='docentes',
            field=models.ManyToManyField(through='academica.CursoProfesor', to='academica.docente'),
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CONTINUA', 'Evaluación Continua'), ('TRIMESTRAL', 'Evaluación Trimestral')], max_length=10)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academica.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL)),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CalificacionEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academica.alumno')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academica.evaluacion')),
            ],
            options={
                'unique_together': {('evaluacion', 'alumno')},
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('LUN', 'Lunes'), ('MAR', 'Martes'), ('MIE', 'Miércoles'), ('JUE', 'Jueves'), ('VIE', 'Viernes'), ('SAB', 'Sábado'), ('DOM', 'Domingo')], max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academica.curso')),
            ],
            options={
                'unique_together': {('curso', 'dia_semana', 'hora_inicio')},
            },
        ),
    ]
